export const BASE_STAR_ALIASES: Record<string, string> = {
  "tử vi": "Tử Vi",
  "thiên cơ": "Thiên Cơ",
  "thái dương": "Thái Dương",
  "vũ khúc": "Vũ Khúc",
  "thiên đồng": "Thiên Đồng",
  "liêm trinh": "Liêm Trinh",
  "thiên phủ": "Thiên Phủ",
  "thái âm": "Thái Âm",
  "tham lang": "Tham Lang",
  "cự môn": "Cự Môn",
  "thiên tướng": "Thiên Tướng",
  "thiên lương": "Thiên Lương",
  "thất sát": "Thất Sát",
  "phá quân": "Phá Quân",
  "lộc tồn": "Lộc Tồn",
  "thiên mã": "Thiên Mã",
  "tả phù": "Tả Phụ",
  "tả phụ": "Tả Phụ",
  "hữu bật": "Hữu Bật",
  "văn xương": "Văn Xương",
  "văn khúc": "Văn Khúc",
  "thiên khôi": "Thiên Khôi",
  "thiên việt": "Thiên Việt",
  "kình dương": "Kình Dương",
  "đà la": "Đà La",
  "hỏa tinh": "Hỏa Tinh",
  "linh tinh": "Linh Tinh",
  "địa không": "Địa Không",
  "địa kiếp": "Địa Kiếp",
  "hóa lộc": "Hóa Lộc",
  "hóa quyền": "Hóa Quyền",
  "hóa khoa": "Hóa Khoa",
  "hóa kỵ": "Hóa Kỵ",
  "tràng sinh": "Trường Sinh",
  "trường sinh": "Trường Sinh",
  "mộc dục": "Mục Dục",
  "quan đới": "Quan Đới",
  "lâm quan": "Lâm Quan",
  "đế vượng": "Đế Vượng",
  "suy": "Suy",
  "bệnh": "Bệnh",
  "tử": "Tử",
  "mộ": "Mộ",
  "tuyệt": "Tuyệt",
  "thai": "Thai",
  "dưỡng": "Dưỡng",
  "bác sĩ": "Bác Sỹ",
  "lực sĩ": "Lực Sỹ",
  "thanh long": "Thanh Long",
  "tiểu hao": "Tiểu Hao",
  "tướng quân": "Tướng Quân",
  "tấu thư": "Tấu Thư",
  "phi liêm": "Phi Liêm",
  "hỷ thần": "Hỷ Thần",
  "bệnh phù": "Bệnh Phù",
  "đại hao": "Đại Hao",
  "phục binh": "Phục Binh",
  "quan phù": "Quan Phù",
  "quan phủ": "Quan Phủ",
  "tam thai": "Tam Thai",
  "bát tọa": "Bát Tọa",
  "long trì": "Long Trì",
  "phụng các": "Phượng Các",
  "phượng các": "Phượng Các",
  "ân quang": "Ân Quang",
  "thiên quý": "Thiên Quý",
  "đài phụ": "Đài Phụ",
  "thai phụ": "Thai Phụ",
  "phong cáo": "Phong Cáo",
  "thiên quan": "Thiên Quan",
  "thiên phúc": "Thiên Phúc",
  "thiên đức": "Thiên Đức",
  "nguyệt đức": "Nguyệt Đức",
  "thiên tài": "Thiên Tài",
  "thiên thọ": "Thiên Thọ",
  "giải thần": "Giải Thần",
  "đào hoa": "Đào Hoa",
  "hồng loan": "Hồng Loan",
  "thiên hỷ": "Thiên Hỷ",
  "hàm trì": "Hàm Trì",
  "thiên diêu": "Thiên Diêu",
  "thiên hình": "Thiên Hình",
  "thiên khốc": "Thiên Khốc",
  "thiên hư": "Thiên Hư",
  "thiên không": "Thiên Không",
  "cô thần": "Cô Thần",
  "quả tú": "Quả Tú",
  "phá toái": "Phá Toái",
  "âm sát": "Âm Sát",
  "hoa cái": "Hoa Cái",
  "thiên vu": "Thiên Vu",
  "thiên trù": "Thiên Trù",
  "thiên nguyệt": "Thiên Nguyệt",
  "thiên thương": "Thiên Thương",
  "thiên sứ": "Thiên Sứ",
  "tuần không": "Tuần",
  "tuần": "Tuần",
  "triệt lộ": "Triệt",
  "triệt": "Triệt",
  "không vong": "Không Vong",
  "thái tuế": "Thái Tuế",
  "tuế phá": "Tuế Phá",
  "bạch hổ": "Bạch Hổ",
  "tang môn": "Tang Môn",
  "điếu khách": "Điếu Khách",
  "long đức": "Long Đức",
};

export const SPECIAL_STAR_ALIASES: Record<string, string> = {
  "tuần không": "Tuần",
  "triệt lộ": "Triệt",
  "tuần": "Tuần",
  "triệt": "Triệt",
};

export const CHINESE_ALIASES: Record<string, string> = {
  "太岁": "Thái Tuế",
  "太歲": "Thái Tuế",
  "岁破": "Tuế Phá",
  "歲破": "Tuế Phá",
  "白虎": "Bạch Hổ",
  "官符": "Quan Phù",
  "丧门": "Tang Môn",
  "喪門": "Tang Môn",
  "吊客": "Điếu Khách",
  "龙池": "Long Trì",
  "龍池": "Long Trì",
  "凤阁": "Phượng Các",
  "鳳閣": "Phượng Các",
  "华盖": "Hoa Cái",
  "華蓋": "Hoa Cái",
};
