import type { ExtraStarRule } from "../config/types";

export const EXTRA_STAR_RULES: ExtraStarRule[] = [
  {
    star: "Lưu Hà",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Dậu",
        Ất: "Tuất",
        Bính: "Mùi",
        Đinh: "Thìn",
        Mậu: "Tỵ",
        Kỷ: "Ngọ",
        Canh: "Thân",
        Tân: "Mão",
        Nhâm: "Hợi",
        Quý: "Dần",
      },
    },
  },
  {
    star: "Đường Phù",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Mùi",
        Ất: "Thân",
        Bính: "Tuất",
        Đinh: "Hợi",
        Mậu: "Tuất",
        Kỷ: "Hợi",
        Canh: "Sửu",
        Tân: "Dần",
        Nhâm: "Thìn",
        Quý: "Tỵ",
      },
    },
  },
  {
    star: "Quốc Ấn",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Tuất",
        Ất: "Hợi",
        Bính: "Sửu",
        Đinh: "Dần",
        Mậu: "Sửu",
        Kỷ: "Dần",
        Canh: "Thìn",
        Tân: "Tỵ",
        Nhâm: "Mùi",
        Quý: "Thân",
      },
    },
  },
  {
    star: "LN Văn Tinh",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Tỵ",
        Ất: "Ngọ",
        Bính: "Thân",
        Đinh: "Dậu",
        Mậu: "Thân",
        Kỷ: "Dậu",
        Canh: "Hợi",
        Tân: "Tý",
        Nhâm: "Dậu",
        Quý: "Mão",
      },
    },
  },
  {
    star: "Thiên Khôi",
    starKey: "thien_khoi",
    source: "vietnamese-extra",
    placeBy: {
      type: "formula",
      formulaId: "thien-khoi-by-year-stem",
    },
  },
  {
    star: "Thiên Việt",
    starKey: "thien_viet",
    source: "vietnamese-extra",
    placeBy: {
      type: "formula",
      formulaId: "thien-viet-by-year-stem",
    },
  },
  {
    star: "Thiên Quan",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Mùi",
        Ất: "Thìn",
        Bính: "Tỵ",
        Đinh: "Dần",
        Mậu: "Mão",
        Kỷ: "Dậu",
        Canh: "Hợi",
        Tân: "Dậu",
        Nhâm: "Tuất",
        Quý: "Ngọ",
      },
    },
  },
  {
    star: "Thiên Phúc",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Dậu",
        Ất: "Thân",
        Bính: "Tý",
        Đinh: "Hợi",
        Mậu: "Mão",
        Kỷ: "Dần",
        Canh: "Ngọ",
        Tân: "Tỵ",
        Nhâm: "Ngọ",
        Quý: "Tỵ",
      },
    },
  },
  {
    star: "Thiên Trù",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearStem",
      map: {
        Giáp: "Tỵ",
        Ất: "Ngọ",
        Bính: "Tý",
        Đinh: "Tỵ",
        Mậu: "Ngọ",
        Kỷ: "Thân",
        Canh: "Dần",
        Tân: "Ngọ",
        Nhâm: "Dậu",
        Quý: "Tuất",
      },
    },
  },
  { star: "Thái Tuế", starKey: "thai_tue", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thai-tue-by-school" } },
  { star: "Thiếu Dương", starKey: "thieu_duong", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thieu-duong-by-school" } },
  { star: "Thiếu Âm", starKey: "thieu_am", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thieu-am-by-thai-tue-cycle" } },
  { star: "Quan Phù", starKey: "quan_phu_thai_tue", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "quan-phu-by-school" } },
  { star: "Tử Phù", starKey: "tu_phu", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "tu-phu-by-school" } },
  { star: "Tuế Phá", starKey: "tue_pha", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "tue-pha-by-school" } },
  { star: "Long Đức", starKey: "long_duc", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "long-duc-by-school" } },
  { star: "Phúc Đức", starKey: "phuc_duc", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "phuc-duc-by-school" } },
  { star: "Điếu Khách", starKey: "dieu_khach", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "dieu-khach-by-school" } },
  { star: "Trực Phù", starKey: "truc_phu", group: "ring", ringName: "Vòng Thái Tuế", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "truc-phu-by-school" } },
  { star: "Bác Sĩ", starKey: "bac_si", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "bac-si-by-loc-ton-ring" } },
  { star: "Lực Sĩ", starKey: "luc_si", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "luc-si-by-loc-ton-ring" } },
  { star: "Thanh Long", starKey: "thanh_long", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thanh-long-by-loc-ton-ring" } },
  { star: "Tiểu Hao", starKey: "tieu_hao", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "tieu-hao-by-loc-ton-ring" } },
  { star: "Tướng Quân", starKey: "tuong_quan", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "tuong-quan-by-loc-ton-ring" } },
  { star: "Tấu Thư", starKey: "tau_thu", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "tau-thu-by-loc-ton-ring" } },
  { star: "Phượng Các", starKey: "phuong_cac", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "phuong-cac-by-year-branch" } },
  { star: "Giải Thần", starKey: "giai_than", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "giai-than-by-school" } },
  { star: "Long Trì", starKey: "long_tri", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "long-tri-by-year-branch" } },
  { star: "Ân Quang", starKey: "an_quang", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "an-quang-by-xuong-khuc-day" } },
  { star: "Thiên Quý", starKey: "thien_quy", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-quy-by-xuong-khuc-day" } },
  { star: "Nguyệt Đức", starKey: "nguyet_duc", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "nguyet-duc-by-year-branch" } },
  { star: "Thiên Đức", starKey: "thien_duc", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-duc-by-year-branch" } },
  { star: "Thiên Hỷ", starKey: "thien_hy", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-hy-by-year-branch" } },
  { star: "Thiên Mã", starKey: "thien_ma", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-ma-by-year-branch" } },
  { star: "Thiên Khốc", starKey: "thien_khoc", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-khoc-by-year-branch" } },
  { star: "Thiên Hư", starKey: "thien_hu", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-hu-by-year-branch" } },
  { star: "Đào Hoa", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "dao-hoa-by-school" } },
  { star: "Hồng Loan", starKey: "hong_loan", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "hong-loan-by-year-branch" } },
  { star: "Hoa Cái", starKey: "hoa_cai", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "hoa-cai-by-year-branch" } },
  { star: "Kiếp Sát", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "kiep-sat-by-school" } },
  { star: "Thiên La", starKey: "thien_la", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "thien-la-fixed" } },
  { star: "Địa Võng", starKey: "dia_vong", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "dia-vong-fixed" } },
  { star: "Đẩu Quân", starKey: "dau_quan", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "dau-quan-by-year-branch-month-hour" } },
  {
    star: "Phá Toái",
    source: "vietnamese-extra",
    placeBy: {
      type: "yearBranch",
      map: {
        Tý: "Tỵ",
        Sửu: "Sửu",
        Dần: "Dậu",
        Mão: "Tỵ",
        Thìn: "Sửu",
        Tỵ: "Dậu",
        Ngọ: "Tỵ",
        Mùi: "Sửu",
        Thân: "Dậu",
        Dậu: "Tỵ",
        Tuất: "Sửu",
        Hợi: "Dậu",
      },
    },
  },
  { star: "Cô Thần", starKey: "co_than", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "co-than-by-year-branch" } },
  { star: "Quả Tú", starKey: "qua_tu", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "qua-tu-by-year-branch" } },
  {
    star: "Thiên Y",
    source: "vietnamese-extra",
    placeBy: {
      type: "monthBranch",
      map: {
        Dần: "Sửu",
        Mão: "Dần",
        Thìn: "Mão",
        Tỵ: "Thìn",
        Ngọ: "Tỵ",
        Mùi: "Ngọ",
        Thân: "Mùi",
        Dậu: "Thân",
        Tuất: "Dậu",
        Hợi: "Tuất",
        Tý: "Hợi",
        Sửu: "Tý",
      },
    },
  },
  {
    star: "Thiên Giải",
    source: "vietnamese-extra",
    placeBy: {
      type: "monthBranch",
      map: {
        Dần: "Thân",
        Mão: "Dậu",
        Thìn: "Tuất",
        Tỵ: "Hợi",
        Ngọ: "Tý",
        Mùi: "Sửu",
        Thân: "Dần",
        Dậu: "Mão",
        Tuất: "Thìn",
        Hợi: "Tỵ",
        Tý: "Ngọ",
        Sửu: "Mùi",
      },
    },
  },
  {
    star: "Địa Giải",
    source: "vietnamese-extra",
    placeBy: {
      type: "monthBranch",
      map: {
        Dần: "Mùi",
        Mão: "Thân",
        Thìn: "Dậu",
        Tỵ: "Tuất",
        Ngọ: "Hợi",
        Mùi: "Tý",
        Thân: "Sửu",
        Dậu: "Dần",
        Tuất: "Mão",
        Hợi: "Thìn",
        Tý: "Tỵ",
        Sửu: "Ngọ",
      },
    },
  },
  {
    star: "Thai Phụ",
    source: "vietnamese-extra",
    placeBy: {
      type: "hourBranch",
      map: {
        Tý: "Ngọ",
        Sửu: "Mùi",
        Dần: "Thân",
        Mão: "Dậu",
        Thìn: "Tuất",
        Tỵ: "Hợi",
        Ngọ: "Tý",
        Mùi: "Sửu",
        Thân: "Dần",
        Dậu: "Mão",
        Tuất: "Thìn",
        Hợi: "Tỵ",
      },
    },
  },
  {
    star: "Phong Cáo",
    source: "vietnamese-extra",
    placeBy: {
      type: "hourBranch",
      map: {
        Tý: "Dần",
        Sửu: "Mão",
        Dần: "Thìn",
        Mão: "Tỵ",
        Thìn: "Ngọ",
        Tỵ: "Mùi",
        Ngọ: "Thân",
        Mùi: "Dậu",
        Thân: "Tuất",
        Dậu: "Hợi",
        Tuất: "Tý",
        Hợi: "Sửu",
      },
    },
  },
  { star: "Hỏa Tinh", starKey: "hoa_tinh", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "hoa-tinh-by-year-branch-hour" } },
  { star: "Linh Tinh", starKey: "linh_tinh", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "linh-tinh-by-year-branch-hour" } },
  { star: "Phi Liêm", starKey: "phi_liem", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "phi-liem-by-loc-ton-ring" } },
  { star: "Hỷ Thần", starKey: "hy_than", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "hy-than-by-loc-ton-ring" } },
  { star: "Bệnh Phù", starKey: "benh_phu", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "benh-phu-by-loc-ton-ring" } },
  { star: "Đại Hao", starKey: "dai_hao", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "dai-hao-by-loc-ton-ring" } },
  { star: "Phục Binh", starKey: "phuc_binh", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "phuc-binh-by-loc-ton-ring" } },
  { star: "Quan Phủ", starKey: "quan_phu_bac_si", group: "ring", ringName: "Vòng Bác Sĩ", source: "vietnamese-extra", placeBy: { type: "formula", formulaId: "quan-phu-by-loc-ton-ring" } },
];
