import type { FiveElement } from "../config/types";

export const STAR_ELEMENTS = {
  "Tử Vi": "tho",
  "Thiên Cơ": "moc",
  "Thái Dương": "hoa",
  "Vũ Khúc": "kim",
  "Thiên Đồng": "thuy",
  "Liêm Trinh": "hoa",
  "Thiên Phủ": "tho",
  "Thái Âm": "thuy",
  "Tham Lang": "moc",
  "Cự Môn": "thuy",
  "Thiên Tướng": "thuy",
  "Thiên Lương": "tho",
  "Thất Sát": "kim",
  "Phá Quân": "thuy",
  "Văn Xương": "kim",
  "Văn Khúc": "thuy",
  "Tả Phụ": "tho",
  "Hữu Bật": "thuy",
  "Thiên Khôi": "hoa",
  "Thiên Việt": "hoa",
  "Lộc Tồn": "tho",
  "Kình Dương": "kim",
  "Đà La": "kim",
  "Hỏa Tinh": "hoa",
  "Linh Tinh": "hoa",
  "Địa Không": "hoa",
  "Địa Kiếp": "hoa",
} satisfies Record<string, FiveElement>;
