import type { VisibleStarPolicy } from "../config/types";

export const AITUVI_VISIBLE_STAR_POLICY: VisibleStarPolicy = {
  mode: "standard",
  showAllRawStars: false,
  showAllMajorStars: true,
  showAllMinorStars: true,
  showAllAdjectiveStars: true,
  showCycleStars: "whitelist",
  cycleStarMode: "whitelist",
  cycleStarWhitelist: [
    "Bác Sĩ",
    "Lực Sĩ",
    "Đại Hao",
    "Tiểu Hao",
    "Quan Phù",
    "Quan Phủ",
    "Tang Môn",
    "Thái Tuế",
    "Bạch Hổ",
    "Điếu Khách",
    "Tướng Quân",
    "Tấu Thư",
    "Thanh Long",
    "Hỷ Thần",
    "Phục Binh",
    "Bệnh Phù",
    "Long Đức",
    "Phi Liêm",
  ],
  hiddenFromVisible: [
    "Quán Tác",
    "Vong Thần",
    "Tuế Kiện",
    "Chỉ Bối",
    "Hối Khí",
    "Tức Thần",
    "Tai Sát",
    "Hàm Trì",
    "Thiên Nguyệt",
    "Không Vong",
  ],
  alwaysVisible: ["Hóa Lộc", "Hóa Quyền", "Hóa Khoa", "Hóa Kỵ", "Tuần", "Triệt"],
  showAnnualStars: true,
};

export const FULL_DEBUG_VISIBLE_STAR_POLICY: VisibleStarPolicy = {
  ...AITUVI_VISIBLE_STAR_POLICY,
  mode: "full",
  showAllRawStars: true,
  showCycleStars: "all",
  cycleStarMode: "all",
  hiddenFromVisible: [],
};
